@startuml
!ROUNDED_STYLE=1
!include <C4/C4_Context>
LAYOUT_TOP_DOWN()

Person(user, "Владелец умного дома", "Просматривает температуру, управляет отоплением")
System_Ext(heat_devices, "Система отопления", "Физические датчики установленные у владельцев в домах")


System(main_system, "Тёплый дом", "Система умного дома Тёплый дом")


Rel(user, main_system, "Регистрирует/деактивирует датчики, просматривает показания, меняет значение температуры/статус датчика")
Rel(main_system, heat_devices, "Получает актуальные показания, осуществляет управление датчиком")

footer PlantUML v.%version(), C4-PlantUML v.C4Version()
@enduml
