@startuml
!ROUNDED_STYLE=1
!include <C4/C4_Component>
!include <logos/nats>
!include <logos/postgresql>
LAYOUT_TOP_DOWN()

Container(api_gateway, "API Gateway", "Apache APISIX")
ContainerQueue(nats, "Message Broker", "Nats", "", nats)
ContainerDb(devices_postgresql, "Database", "PostgreSQL", "", postgresql)
System_Ext(smart_device, "Система умных устройств", "Физические устройства партнера установленные у владельцев в домах")



Container_Boundary(device_management, "Device Management Service") {
    Component(device_api, "Device REST Controller", "FastAPI Router", "Регистрация, просмотр, деактивация устройств, смена статуса и показателей устройств")
    Component(device_nats_consumer, "Command Consumer", "NATS JetStream Consumer", "Забирает команды на взаимодействие с умными устройствами из брокера")


    Component(device_service, "Device Service", "Python", "Бизнес-логика: проверка на то что пользователь может видеть и изменять, обращение к необходимому адаптеру и репозиторию")


    Component(device_repo, "Device Repository", "SQLAlchemy (async)", "CRUD операций с устройствами")
    Component(adapter_factory, "Protocol Adapter Factory", "Python", "Выбор нужного адаптера по типу устройства")


    Component(mqtt_adapter, "MQTT Adapter", "Python", "Реализация протокола MQTT")
    Component(rest_polling_adapter, "REST Polling Adapter", "Python", "")
    Component(unknown_adapter, "Unknown Yet Adapter", "Python", "Реализация на текущий момент еще неизвестного протокола")
}



Rel(api_gateway, device_api, "REST API")
Rel(nats, device_nats_consumer, "Consume on specific subject")



Rel(device_api, device_service, "Uses")
Rel(device_nats_consumer, device_service, "Uses")



Rel(device_service, device_repo, "Query")
Rel(device_service, adapter_factory, "Получает адаптер по типу устройства из БД")



Rel(device_repo, devices_postgresql, "SQL")



Rel(adapter_factory, mqtt_adapter, "Creates")
Rel(adapter_factory, rest_polling_adapter, "Creates")
Rel(adapter_factory, unknown_adapter, "Creates")


Rel(mqtt_adapter, smart_device, "MQTT")
Rel(rest_polling_adapter, smart_device, "REST API")
Rel(unknown_adapter, smart_device, "Various")

@enduml