@startuml
!ROUNDED_STYLE=1
!include <C4/C4_Component>
!include <logos/nats>
LAYOUT_TOP_DOWN()

Container(api_gateway, "API Gateway", "Apache APISIX")
ContainerQueue(nats, "Message Broker", "Nats", "", nats)
ContainerDb(click, "Column oriented database", "Clickhouse", "")



Container_Boundary(telemetry, "Telemetry Service") {
    Component(telemetry_ingest_api, "Telemetry Ingest Controller", "FastAPI Router", "Приём показаний устройств")
    Component(telemetry_query_api, "Telemetry Query Controller", "FastAPI Router", "Просмотр и агрегация показаний")


    Component(telemetry_service, "Telemetry Service", "Python", "Валидация показаний, проcмотр и агрегация")


    Component(telemetry_repo, "Telemetry Repository", "clickhouse-connect (async)", "Запись/чтение показаний")
    Component(telemetry_nats_publisher, "Telemetry Event Publisher", "NATS JetStream Publisher", "Публикация события телеметрии")
}



Rel(api_gateway, telemetry_ingest_api, "REST API")
Rel(api_gateway, telemetry_query_api, "REST API")



Rel(telemetry_ingest_api, telemetry_service, "Uses")
Rel(telemetry_query_api, telemetry_service, "Uses")



Rel(telemetry_service, telemetry_repo, "Query")
Rel(telemetry_service, telemetry_nats_publisher, "Publish")



Rel(telemetry_repo, click, "SQL")
Rel(telemetry_nats_publisher, nats, "Produce")

@enduml
