@startuml
!ROUNDED_STYLE=1
!include <C4/C4_Component>
LAYOUT_TOP_DOWN()

Container(api_gateway, "API Gateway", "Apache APISIX")
ContainerDb(s3_storage, "Object Storage", "S3")
System_Ext(smart_device, "Система умных устройств", "Физические устройства партнера установленные у владельцев в домах")



Container_Boundary(video_monitoring, "Video Monitoring Service") {
    Component(video_api, "Video REST/WS Controller", "FastAPI Router + WebSocket", "Запросы live-потока и видеоархива")

    Component(video_service, "Video Service", "Python", "Оркестрация сессий просмотра, работа с архивом")

    Component(signaling, "WebRTC Signaling Component", "Python", "Установление потока с камерой")
    Component(archive_repo, "Archive Repository", "aioboto3 / S3 client", "Сохранение и получение видеозаписей с камер")
}



Rel(api_gateway, video_api, "WebSockets / REST API")



Rel(video_api, video_service, "Uses")



Rel(video_service, signaling, "Initialize session")
Rel(video_service, archive_repo, "Query")



Rel(signaling, smart_device, "WebRTC")
Rel(archive_repo, s3_storage, "S3 API")

@enduml
